# Site settings
title: 旧·时光 | Time
SEOTitle: 旧·时光 | YoungChen's Blog
header-img: img/bg1.jpg
email: Chen.Jiayang@foxmail.com
description: "Something that stays in your mind will someday spring up in your life."
keyword: "YoungChen,主页,博客,Java,Redis,分布式,MySQL"
url: "http://chenjiayang.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: true
weibo_username:     u/3284056213
zhihu_username:     EasonChen_7
github_username:    jiayangchen
#twitter_username:  huxpro
#facebook_username:  jiayangchen
linkedin_username:  嘉扬-陈-04463a117
csdn_username: chen_kkw

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
paginate: 15
port: 4001

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Livere settings
livere_userid: MTAyMC8zMjgxNS85Mzc2
# Disqus settings
#disqus_username: jiayangchen

# Duoshuo settings
#duoshuo_username: jiayangchen
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 57bc9aa8fa52f13b45b8480cacb9cc67
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "从来不求时间为我搁浅..."
sidebar-avatar: /img/avatar.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "yeming",
        href: "http://yeming.me/"
    },
    {
        title: "田守支Java技术博客",
        href: "http://tianshouzhi.com/"
    },
    {
        title: "Ivy-End",
        href: "http://www.ivy-end.com/"
    },
    {
        title: "青菜萝卜",
        href: "http://www.huding.me/index.html"
    },
    {
        title: "Commouse",
        href: "http://www.commouse.me"
    },
    {
        title: "Gaocegege",
        href: "http://www.gaocegege.com"
    },
    {
        title: "嘉美伯爵",
        href: "http://blog.fovegage.cn/"
    }
]

# Photos
photos: [
    {
        url: "http://o9oomuync.bkt.clouddn.com/blogIMG_20180623_132723_HDR.jpg",
        title: "罗中立美术馆",
        date: "2018.06",
        location: "重庆四川美术学院"
    },
    {
        url: "http://o9oomuync.bkt.clouddn.com/blogIMG_20180625_150859.jpg",
        title: "艺术楼",
        date: "2018.06",
        location: "成都东郊记忆"
    },
    {
        url: "http://o9oomuync.bkt.clouddn.com/blogIMG_20180626_161617.jpg",
        title: "青铜面具人像",
        date: "2018.06",
        location: "四川博物馆"
    },
    {
        url: "http://o9oomuync.bkt.clouddn.com/bloghometown.jpeg",
        title: "年关的家乡",
        date: "2018.02",
        location: "张家港乐余镇"
    },
    {
        url: "http://o9oomuync.bkt.clouddn.com/blog%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20170921164059.jpg",
        title: "在东南偶遇拍毕业照",
        date: "2017.09",
        location: "东南大学四牌楼校区"
    },
    {
        url: "http://o9oomuync.bkt.clouddn.com/blog%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20170921161442.jpg",
        title: "台风来临前的晚霞",
        date: "2017.09",
        location: "东 26 楼寝室阳台"
    },
    {
        url: "/photos/love.jpg",
        title: "球场看台的求婚",
        date: "2017.05",
        location: "上海八万人体育场"
    },
    {
        url: "/photos/Hackathon.jpg",
        title: "2016 Microsoft Penta-Hackathon",
        date: "2016.11",
        location: "微软紫竹亚研院"
    },
    {
        url: "/photos/binjiang_park.jpg",
        title: "初春公园出游掠影",
        date: "2016.04",
        location: "闵行区滨江公园外"
    },
    {
        url: "/photos/military_training.jpg",
        title: "大一暑假军训晚会",
        date: "2015.09",
        location: "上海交通大学霍英东体育馆"
    },
    {
        url: "/photos/stadium.jpg",
        title: "2015 年中超联赛首轮",
        date: "2015.03",
        location: "上海八万人体育场"
    },
    {
        url: "/photos/museum.jpg",
        title: "唐朝彩色侍女佣像",
        date: "2016 年中秋",
        location: "上海博物馆"
    }
]
